import type { QuestionnaireQuestion } from "./types";

// The real 65-question Regodit vendor security questionnaire
// (source: "Regodit_Comprehensive_Vendor_Security_Questionnaire_Clean.xlsx",
// sheet "Vendor Security Responses").
export const SECURITY_QUESTIONS: QuestionnaireQuestion[] = [
  {
    category: "Governance",
    id: "q1-governance",
    order: 1,
    priority: "high",
    requiredDetails: ["policy_reference", "owner", "review_frequency"],
    text: "Does your organization have a formal Information Security Program established?",
  },
  {
    category: "Governance",
    id: "q2-governance",
    order: 2,
    priority: "high",
    requiredDetails: ["policy_reference", "owner", "review_frequency"],
    text: "Does your organization have a published set of Information Security policies, standards and procedures?",
  },
  {
    category: "Governance",
    id: "q3-governance",
    order: 3,
    priority: "high",
    requiredDetails: ["policy_reference", "owner", "review_frequency"],
    text: "Does your organization have a public information security policy?",
  },
  {
    category: "Governance",
    id: "q4-governance",
    order: 4,
    priority: "high",
    requiredDetails: ["policy_reference", "owner", "review_frequency"],
    text: "Does your organization document role descriptions including relevant cybersecurity & data protection responsibilities?",
  },
  {
    category: "Governance",
    id: "q5-governance",
    order: 5,
    priority: "high",
    requiredDetails: ["policy_reference", "owner", "review_frequency"],
    text: "Is there a procedure in place for overseeing cybersecurity and data protection controls, that includes how issues are escalated to leadership?",
  },
  {
    category: "Third-Party Risk Management",
    id: "q6-third-party-risk-man",
    order: 6,
    priority: "high",
    requiredDetails: ["process", "scope", "review_frequency"],
    text: "Will you be using any contractors or sub-contractors to complete the engagement with Client XYZ?",
  },
  {
    category: "Third-Party Risk Management",
    id: "q7-third-party-risk-man",
    order: 7,
    priority: "high",
    requiredDetails: ["process", "scope", "review_frequency"],
    text: "Do you have a third-party risk management program/policy in place?",
  },
  {
    category: "Third-Party Risk Management",
    id: "q8-third-party-risk-man",
    order: 8,
    priority: "high",
    requiredDetails: ["process", "scope", "review_frequency"],
    text: "Please attach your Third-Party Risk Management Policy.",
  },
  {
    category: "Third-Party Risk Management",
    id: "q9-third-party-risk-man",
    order: 9,
    priority: "high",
    requiredDetails: ["process", "scope", "review_frequency"],
    text: "Does your third-party risk management program include supply chain protections?",
  },
  {
    category: "Third-Party Risk Management",
    id: "q10-third-party-risk-man",
    order: 10,
    priority: "high",
    requiredDetails: ["process", "scope", "review_frequency"],
    text: "Do your vendor and subcontractor agreements include clauses requiring adherence to cybersecurity and data privacy standards, and do these requirements flow down to all applicable subcontractors and suppliers?",
  },
  {
    category: "Security Awareness & Training",
    id: "q11-security-awareness-t",
    order: 11,
    priority: "medium",
    requiredDetails: ["frequency", "scope", "owner"],
    text: "Do you provide security awareness training at onboarding and at least annually thereafter for all personnel including contractors?",
  },
  {
    category: "Security Awareness & Training",
    id: "q12-security-awareness-t",
    order: 12,
    priority: "medium",
    requiredDetails: ["frequency", "scope", "owner"],
    text: "How frequently are employees trained on policies in your organization?",
  },
  {
    category: "Security Awareness & Training",
    id: "q13-security-awareness-t",
    order: 13,
    priority: "medium",
    requiredDetails: ["frequency", "scope", "owner"],
    text: "Does your organization provide role based security awareness training at least annually?",
  },
  {
    category: "Privacy",
    id: "q14-privacy",
    order: 14,
    priority: "high",
    requiredDetails: ["scope", "legal_basis", "current_state"],
    text: "Does your organization have privacy controls and or Data Privacy program in place?",
  },
  {
    category: "Privacy",
    id: "q15-privacy",
    order: 15,
    priority: "high",
    requiredDetails: ["scope", "legal_basis", "current_state"],
    text: "Will your personnel or your product require access to sensitive data (i.e PII, PI, PHI) to complete the engagement with Regodit?",
  },
  {
    category: "Privacy",
    id: "q16-privacy",
    order: 16,
    priority: "high",
    requiredDetails: ["scope", "legal_basis", "current_state"],
    text: "Please provide a copy of your data retention schedule and secure disposal procedures",
  },
  {
    category: "Privacy",
    id: "q17-privacy",
    order: 17,
    priority: "high",
    requiredDetails: ["scope", "legal_basis", "current_state"],
    text: "Do you have a privacy policy in place? If so, please provide the attachment or URL.",
  },
  {
    category: "Privacy",
    id: "q18-privacy",
    order: 18,
    priority: "high",
    requiredDetails: ["scope", "legal_basis", "current_state"],
    text: "Does your organization ensure privacy requirements are extended to contractors and service providers through contractual agreements, and that roles and responsibilities concerning data privacy are clearly understood and documented?",
  },
  {
    category: "Data Security",
    id: "q19-data-security",
    order: 19,
    priority: "high",
    requiredDetails: ["systems", "scope", "algorithm_or_provider"],
    text: "Do you, or any third party you use to deliver services to Client XYZ, store sensitive information outside the United States? If so, where?",
  },
  {
    category: "Data Security",
    id: "q20-data-security",
    order: 20,
    priority: "high",
    requiredDetails: ["systems", "scope", "algorithm_or_provider"],
    text: "Do you require data-at-rest encryption for sensitive data?",
  },
  {
    category: "Data Security",
    id: "q21-data-security",
    order: 21,
    priority: "high",
    requiredDetails: ["systems", "scope", "algorithm_or_provider"],
    text: "Do you require data-in-transit encryption for sensitive data? If so, please describe the encryption protocols used.",
  },
  {
    category: "Data Security",
    id: "q22-data-security",
    order: 22,
    priority: "high",
    requiredDetails: ["systems", "scope", "algorithm_or_provider"],
    text: "Will Regodit data be stored on site, in a data center, or by a third party?",
  },
  {
    category: "Data Security",
    id: "q23-data-security",
    order: 23,
    priority: "high",
    requiredDetails: ["systems", "scope", "algorithm_or_provider"],
    text: "Do you have data retention policies and procedures for the secure disposal of information?",
  },
  {
    category: "Data Security",
    id: "q24-data-security",
    order: 24,
    priority: "high",
    requiredDetails: ["systems", "scope", "algorithm_or_provider"],
    text: "If providing a product or SaaS platform that will access, store, or process Client XYZ data, are you able to provide applicable data flow diagrams showing how Regodit's data will flow through the tool upon request?",
  },
  {
    category: "Physical Security",
    id: "q25-physical-security",
    order: 25,
    priority: "medium",
    requiredDetails: ["scope", "controls", "current_state"],
    text: "Is there a policy in place for physical security requirements for your business?",
  },
  {
    category: "Physical Security",
    id: "q26-physical-security",
    order: 26,
    priority: "medium",
    requiredDetails: ["scope", "controls", "current_state"],
    text: "Do you require physical access to any Client XYZ locations to complete your engagement?",
  },
  {
    category: "Physical Security",
    id: "q27-physical-security",
    order: 27,
    priority: "medium",
    requiredDetails: ["scope", "controls", "current_state"],
    text: "Are you willing to accept and acknowledge the expectations outlined in Client XYZ's Visitor Management document?",
  },
  {
    category: "Physical Security",
    id: "q28-physical-security",
    order: 28,
    priority: "medium",
    requiredDetails: ["scope", "controls", "current_state"],
    text: "Does your organization have procedures in place to track assets that are brought onto Client XYZ sites?",
  },
  {
    category: "Physical Security",
    id: "q29-physical-security",
    order: 29,
    priority: "medium",
    requiredDetails: ["scope", "controls", "current_state"],
    text: "Can you provide your organization's data protection policy, including evidence of physical safeguards for devices used onsite if requested?",
  },
  {
    category: "Web Application Security",
    id: "q30-web-application-secu",
    order: 30,
    priority: "medium",
    requiredDetails: ["scope", "controls", "frequency"],
    text: "Will Client XYZ be using a web application provided by you?",
  },
  {
    category: "Web Application Security",
    id: "q31-web-application-secu",
    order: 31,
    priority: "medium",
    requiredDetails: ["scope", "controls", "frequency"],
    text: "What is the name of your web application?",
  },
  {
    category: "Web Application Security",
    id: "q32-web-application-secu",
    order: 32,
    priority: "medium",
    requiredDetails: ["scope", "controls", "frequency"],
    text: "What is the function/purpose of your web application?",
  },
  {
    category: "Web Application Security",
    id: "q33-web-application-secu",
    order: 33,
    priority: "medium",
    requiredDetails: ["scope", "controls", "frequency"],
    text: "How do you report application security vulnerabilities?",
  },
  {
    category: "Web Application Security",
    id: "q34-web-application-secu",
    order: 34,
    priority: "medium",
    requiredDetails: ["scope", "controls", "frequency"],
    text: "Does your web application have an SSL/TLS certificate?",
  },
  {
    category: "Web Application Security",
    id: "q35-web-application-secu",
    order: 35,
    priority: "medium",
    requiredDetails: ["scope", "controls", "frequency"],
    text: "Does your application offer single sign-on (SSO) or are there plans to implement/offer SSO in the near future? If plans to implement in near future, include an implementation date in your justification.",
  },
  {
    category: "Secure Coding",
    id: "q36-secure-coding",
    order: 36,
    priority: "medium",
    requiredDetails: ["process", "scope", "owner"],
    text: "Do you have policies, procedures or standards in place for secure development practices?",
  },
  {
    category: "Secure Coding",
    id: "q37-secure-coding",
    order: 37,
    priority: "medium",
    requiredDetails: ["process", "scope", "owner"],
    text: "Do you utilize Secure Coding Principles - (Detailed logging, encrypted credentials, etc.)?",
  },
  {
    category: "Vulnerability Management",
    id: "q38-vulnerability-manage",
    order: 38,
    priority: "high",
    requiredDetails: ["performed", "frequency", "scope", "owner"],
    text: "Are internal vulnerability scans performed?",
  },
  {
    category: "Vulnerability Management",
    id: "q39-vulnerability-manage",
    order: 39,
    priority: "high",
    requiredDetails: ["performed", "frequency", "scope", "owner"],
    text: "On what cadence are vulnerability scans performed?",
  },
  {
    category: "Vulnerability Management",
    id: "q40-vulnerability-manage",
    order: 40,
    priority: "high",
    requiredDetails: ["performed", "frequency", "scope", "owner"],
    text: "What are the documented remediation timelines for critical and high patches?",
  },
  {
    category: "Business Continuity & Disaster Recovery",
    id: "q41-business-continuity-",
    order: 41,
    priority: "medium",
    requiredDetails: ["process", "frequency", "owner"],
    text: "What is the process for disaster recovery and backups?",
  },
  {
    category: "Business Continuity & Disaster Recovery",
    id: "q42-business-continuity-",
    order: 42,
    priority: "medium",
    requiredDetails: ["process", "frequency", "owner"],
    text: "Please provide a copy of your BC/DR policy for review.",
  },
  {
    category: "Incident Response",
    id: "q43-incident-response",
    order: 43,
    priority: "high",
    requiredDetails: ["process", "owner", "notification_timeline"],
    text: "Do you keep a record of security events?",
  },
  {
    category: "Incident Response",
    id: "q44-incident-response",
    order: 44,
    priority: "high",
    requiredDetails: ["process", "owner", "notification_timeline"],
    text: "Do you monitor the security of your wireless networks?",
  },
  {
    category: "Incident Response",
    id: "q45-incident-response",
    order: 45,
    priority: "high",
    requiredDetails: ["process", "owner", "notification_timeline"],
    text: "Do you have an incident response plan in place? If yes, describe briefly.",
  },
  {
    category: "Incident Response",
    id: "q46-incident-response",
    order: 46,
    priority: "high",
    requiredDetails: ["process", "owner", "notification_timeline"],
    text: "How often is your Incident Response Plan Tested?(Drop Down)",
  },
  {
    category: "Incident Response",
    id: "q47-incident-response",
    order: 47,
    priority: "high",
    requiredDetails: ["process", "owner", "notification_timeline"],
    text: "Do you have a policy requiring prompt notice to third parties regarding information security events affecting your organization?",
  },
  {
    category: "Incident Response",
    id: "q48-incident-response",
    order: 48,
    priority: "high",
    requiredDetails: ["process", "owner", "notification_timeline"],
    text: "Regardless of materiality, have you had a security event in the last 5 years?",
  },
  {
    category: "Incident Response",
    id: "q49-incident-response",
    order: 49,
    priority: "high",
    requiredDetails: ["process", "owner", "notification_timeline"],
    text: "Do you outsource security functions to third-party providers?",
  },
  {
    category: "Network & Endpoint Security",
    id: "q50-network-endpoint-sec",
    order: 50,
    priority: "high",
    requiredDetails: ["systems", "scope", "current_state"],
    text: "Do you use anti virus software to protect your devices? If yes, describe.",
  },
  {
    category: "Network & Endpoint Security",
    id: "q51-network-endpoint-sec",
    order: 51,
    priority: "high",
    requiredDetails: ["systems", "scope", "current_state"],
    text: "Will your organization be accessing Client XYZ's network?",
  },
  {
    category: "Network & Endpoint Security",
    id: "q53-network-endpoint-sec",
    order: 53,
    priority: "high",
    requiredDetails: ["systems", "scope", "current_state"],
    text: "Please list out all authorized personnel, including first and last names and e-mail addresses from your organization that will have access to Client XYZ's assets or network.",
  },
  {
    category: "Network & Endpoint Security",
    id: "q54-network-endpoint-sec",
    order: 54,
    priority: "high",
    requiredDetails: ["systems", "scope", "current_state"],
    text: "Please submit a network architecture diagram and details of your endpoint protection measures, including how your organization complies with firewall and DNS security standards when accessing XYZ's networks.",
  },
  {
    category: "Asset Management",
    id: "q55-asset-management",
    order: 55,
    priority: "medium",
    requiredDetails: ["scope", "process", "current_state"],
    text: "Do you keep an inventory of information technology (IT) assets and software?",
  },
  {
    category: "Asset Management",
    id: "q56-asset-management",
    order: 56,
    priority: "medium",
    requiredDetails: ["scope", "process", "current_state"],
    text: "Does your organization have identity and access controls in place?",
  },
  {
    category: "Asset Management",
    id: "q57-asset-management",
    order: 57,
    priority: "medium",
    requiredDetails: ["scope", "process", "current_state"],
    text: "Does your organization leverage role-based access control?",
  },
  {
    category: "Asset Management",
    id: "q58-asset-management",
    order: 58,
    priority: "medium",
    requiredDetails: ["scope", "process", "current_state"],
    text: "Do you limit and periodically review user access privileges and controls?",
  },
  {
    category: "Asset Management",
    id: "q59-asset-management",
    order: 59,
    priority: "medium",
    requiredDetails: ["scope", "process", "current_state"],
    text: "What is the cadence of your access reviews?(Drop Down)",
  },
  {
    category: "Asset Management",
    id: "q60-asset-management",
    order: 60,
    priority: "medium",
    requiredDetails: ["scope", "process", "current_state"],
    text: "Does your organization require replay-resistant authentication mechanisms such as OTP or MFA?",
  },
  {
    category: "Asset Management",
    id: "q61-asset-management",
    order: 61,
    priority: "medium",
    requiredDetails: ["scope", "process", "current_state"],
    text: "Are the external authenticators in use, NIST compliant?",
  },
  {
    category: "Asset Management",
    id: "q62-asset-management",
    order: 62,
    priority: "medium",
    requiredDetails: ["scope", "process", "current_state"],
    text: "Does your organization enforce the principle of least privilege?",
  },
  {
    category: "Risk Assessment",
    id: "q63-risk-assessment",
    order: 63,
    priority: "medium",
    requiredDetails: ["process", "frequency", "owner"],
    text: "Do you conduct information security risk assessments at least annually?",
  },
  {
    category: "Risk Assessment",
    id: "q64-risk-assessment",
    order: 64,
    priority: "medium",
    requiredDetails: ["process", "frequency", "owner"],
    text: "How do you prioritize critical assets for your organization?",
  },
  {
    category: "Risk Assessment",
    id: "q65-risk-assessment",
    order: 65,
    priority: "medium",
    requiredDetails: ["process", "frequency", "owner"],
    text: "Does your organization conduct penetration testing at least annually?",
  },
  {
    category: "Risk Assessment",
    id: "q66-risk-assessment",
    order: 66,
    priority: "medium",
    requiredDetails: ["process", "frequency", "owner"],
    text: "Have the findings from the most recent penetration test been remediated?",
  },
];

// The hackathon demo is an investigation into the controls called out in the
// brief. Keep the full vendor question bank available for future expansion,
// but make the analyst workspace and export answer the questions that matter
// to this workflow instead of rendering every unrelated vendor field.
export const FOCUSED_SECURITY_QUESTIONS: QuestionnaireQuestion[] = [
  {
    category: "Identity & Access",
    id: "mfa-enabled",
    order: 1,
    priority: "high",
    requiredDetails: ["systems", "scope", "current_state"],
    text: "Is MFA enabled for workforce and privileged access?",
  },
  {
    category: "Data Security",
    id: "customer-data-storage-location",
    order: 2,
    priority: "high",
    requiredDetails: ["systems", "scope", "location"],
    text: "Where is customer data stored?",
  },
  {
    category: "Data Security",
    id: "customer-data-encryption-at-rest",
    order: 3,
    priority: "high",
    requiredDetails: ["systems", "scope", "algorithm_or_provider"],
    text: "Is customer data encrypted at rest?",
  },
  {
    category: "Business Continuity",
    id: "backups-performed",
    order: 4,
    priority: "high",
    requiredDetails: ["performed", "frequency", "automation", "retention"],
    text: "How often are backups performed, and are they automated?",
  },
  {
    category: "Vulnerability Management",
    id: "vulnerability-scans-performed",
    order: 5,
    priority: "high",
    requiredDetails: ["performed", "frequency", "scope"],
    text: "Do you conduct vulnerability scans?",
  },
  {
    category: "Identity & Access",
    id: "production-access",
    order: 6,
    priority: "high",
    requiredDetails: ["people_or_roles", "approval", "logging"],
    text: "Who has access to production systems?",
  },
  {
    category: "Personnel Security",
    id: "employee-offboarding",
    order: 7,
    priority: "high",
    requiredDetails: ["process", "timing", "owner", "device_handling"],
    text: "Do you have an employee offboarding process?",
  },
];

// Supplemental controls remain available to the analyst when an employee
// asks about them, but are intentionally outside the seven-question export.
export const SUPPLEMENTAL_SECURITY_QUESTIONS: QuestionnaireQuestion[] = [
  {
    category: "Personnel Security",
    id: "employee-background-checks",
    order: 1,
    priority: "medium",
    requiredDetails: ["scope", "timing", "owner"],
    text: "Do you perform employee background checks?",
  },
];

const QUESTION_ID_ALIASES: Record<string, string> = {
  backups: "backups-performed",
  "customer-data-encryption": "customer-data-encryption-at-rest",
  "customer-data-storage": "customer-data-storage-location",
  "employee-offboarding-process": "employee-offboarding",
  "production-system-access": "production-access",
  "vulnerability-scan": "vulnerability-scans-performed",
  "vulnerability-scans": "vulnerability-scans-performed",
};

export function normalizeQuestionId(id: string) {
  const normalizedId = id.trim().replaceAll("_", "-");
  return QUESTION_ID_ALIASES[normalizedId] ?? normalizedId;
}

export function getQuestion(id: string) {
  const canonicalId = normalizeQuestionId(id);
  return [
    ...FOCUSED_SECURITY_QUESTIONS,
    ...SUPPLEMENTAL_SECURITY_QUESTIONS,
    ...SECURITY_QUESTIONS,
  ].find((question) => question.id === canonicalId);
}
